### ISSUE TITLE
Support managed UEFI variables

### ISSUE THREAD

**Issue by ikeydoherty** [clearlinux/clr-boot-manager#36]
`clr-boot-manager` should retain and maintain the UEFI variables (nvvars) for it's own entry, during boot and upgrades. Specifically a policy must be introduced to allow UEFI variables to be configured from an installation process (i.e. `swupd` from the Clear Linux installer)

**Comment by ikeydoherty** [comment]
@bryteise any thoughts on how you want this handled? Mostly thinking about that email earlier today.

**Comment by bryteise** [comment]
I'd probably say link off to efivars and implement something along the lines of using a configuration file to decide if the entry gets priority or not. We could add other ister ui hooks for this but it should be coordinated between the two. What other things aside from priority do you think a user would really want to configure?

**Comment by ikeydoherty** [comment]
Stable ABI or static link it.. ?

**Comment by bryteise** [comment]
Static link.

On Jan 23, 2017 4:18 PM, "Ikey Doherty" <notifications@github.com> wrote:

Stable ABI or static link it.. ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ikeydoherty/clr-boot-manager/issues/36#issuecomment-274661296>,
or mute the thread

**Comment by bryteise** [comment]
Hrm so this isn't in place how it was planned but since cbm does support configuring its own boot entry via EFI variables today I'd say this is complete. Closing...
